Added Uses to Cactus/Sugar Charcoal/Coke
GTNH-Museum/GTplusplus pull request #192
Opened 2022-05-24 14:56 UTC by Steelux8

- Changed the existing Industrial Coke Oven recipes to make them a lot faster than the Charcoal recipes, since they only make 1 at a time compared to the Charcoal recipes' 5;
- Added uses to these items, such as Charcoal Byproducts output, Wood Tar extraction, Coal Tar and Gas, and also CO and CO2.

As per https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10233, Charcoal and Coal Coke can be made from Cactus and Sugar Cane, although with less fuel value than the original versions. However, these don't have most of the uses that those do, being mostly used as furnace fuel and little else. With this PR, I changed and created recipes so that these can be used similarly to Wood and Charcoal, although with less available uses and automations, which leave Wood and Charcoal as the best options after the first couple of tiers.

2022-06-07 09:02 UTC, Steelux8 commented
Still waiting for approval on this to close the issue mentioned above.

2022-06-07 09:15 UTC, GlodBlock requested changes

2022-06-07 09:15 UTC, GlodBlock commented on src/main/java/gtPlusPlus/xmod/railcraft/HANDLER_Railcraft.java
> +			CORE.RA.addCokeOvenRecipe(aOutputs[i], CI.getNumberedCircuit(6), FluidUtils.getFluidStack("steam", 100), FluidUtils.getFluidStack("fluid.coalgas", 300), Materials.Ash.getDustSmall(1), 60, 240);
remove coal tar/gas recipe or change them into wood tar/gas.

2022-06-10 21:15 UTC, Steelux8 commented on src/main/java/gtPlusPlus/xmod/railcraft/HANDLER_Railcraft.java
> +			CORE.RA.addCokeOvenRecipe(aOutputs[i], CI.getNumberedCircuit(6), FluidUtils.getFluidStack("steam", 100), FluidUtils.getFluidStack("fluid.coalgas", 300), Materials.Ash.getDustSmall(1), 60, 240);
It's done. I liked the renewable Coal Tar and Gas, but Coal itself is already renewable, and making the Wood versions from these makes more sense.

2022-06-10 21:20 UTC, Dream-Master approved these changes

2022-06-10 21:20 UTC, merged