Fix fertilizer usage in Crop Manager
GTNH-Museum/GTplusplus pull request #217
Opened 2022-06-16 03:03 UTC by xSkewer

Haven't tested ingame yet but it should work. Also increases the fertilizer cap to 200, which is what Forestry farms are at.

2022-06-16 11:25 UTC, kuba6000 requested changes

2022-06-16 11:25 UTC, kuba6000 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_CropHarvestor.java
> +			aCrop.setNutrientStorage(getNutrientStorage() + 100);
I think you forgot something
```suggestion
			aCrop.setNutrientStorage(aCrop.getNutrientStorage() + 100);
```

2022-06-16 13:36 UTC, kuba6000 approved these changes
Ok

2022-06-16 14:16 UTC, merged

2022-06-16 23:54 UTC, draknyte1 commented
> Haven't tested ingame yet but it should work. Also increases the fertilizer cap to 200, which is what Forestry farms are at.

IC2 states the max should be 100. The values for the crop manager are based on IC2. 

Forestry should be nerfed, it’s essentially giving crops free fert by setting to 200.

2022-06-17 00:06 UTC, xSkewer commented
> IC2 states the max should be 100. The values for the crop manager are based on IC2.
> 
> Forestry should be nerfed, it’s essentially giving crops free fert by setting to 200.

You can hand apply fertilizer up to 199.