Add the Nuclear Salt Processing Plant
GTNH-Museum/GTplusplus pull request #607
Opened 2023-04-23 18:35 UTC by Steelux8

Enable the multi when loading

Config handler for the multi

More enabling

Multi controller recipe

Add necessary recipes to new, custom recipemap

Add function to generate new recipes

Declare item for the controller

Define recipe map for the multi

Render NEI page for the recipemap properly

Change P output from 7 to 6 in recipe

Spotless apply

2023-04-26 17:37 UTC, minecraft7771 requested changes
Only code review, not balance review

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/core/handler/COMPAT_HANDLER.java
> +import gtPlusPlus.xmod.gregtech.registration.gregtech.*;
boubou was in favor of not using wildcards. So please revert. Possibly see here https://intellij-support.jetbrains.com/hc/en-us/community/posts/206203659-Turn-off-Wildcard-imports- how to tell intelliJ not to automatically do that.

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +    public void onRightclick(EntityPlayer player) {}
Remove this function if not needed.

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +        return super.onRunningTick(aStack);
Remove this function if  you only call super.

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +                .addCasingInfo("IV Machine Casing", 58).addCasingInfo("Thermally Insulated Casing", 1)
`addCasingInfo` is deprecated. You can use `addCasingInfoMin` for the old behavior or give exact casing requirements with `addCasingInfoExactly` and `addCasingInfoRange`

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +        return checkPiece(mName, 4, 2, 0) && mEnergyHatches.size() == 2 && mMufflerHatches.size() == 2 && checkHatch();
Override the function `checkHatch()`. Call `super.checkHatch()` and then check muffler and energy hatches there.

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +        if (inputSeparation) {
If you want to use inputSeperation you need to override `isInputSeperationButtonEnabled()`

2023-04-26 17:37 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechNuclearSaltProcessingPlant.java
> +    private static void run1() {
If you only want to add this one machine, then inline the methods-content into `run()`

2023-04-26 18:03 UTC, chochem commented
In terms of balance this sounds reasonable. LFTR is not exactly popular and this could bring some spice into it. Late IV recipe and numbers seem good.

2023-04-30 23:13 UTC, Steelux8 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +        if (inputSeparation) {
I did not enable it right away because, currently, there are no recipes with item inputs.

2023-04-30 23:25 UTC, Steelux8 commented
I think I made all the requested changes.

2023-05-01 07:39 UTC, minecraft7771 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_NuclearSaltProcessingPlant.java
> +        if (inputSeparation) {
Either it should be enabled or the inputSeparation -logicshould be removed imo. If in the future another person comes across the code they'll probably see it as bug and do either anyway.

2023-05-01 10:36 UTC, minecraft7771 approved these changes

2023-05-01 10:37 UTC, merged