Advanced boiler fix
GTNH-Museum/GTplusplus pull request #686
Opened 2023-07-09 21:11 UTC by Lyfts

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13872 

Been broken for 2 years, even if the GTPP method had worked it would spam the vent sound repeatedly as soon as steam filled up.
Tested and works exactly as anticipated. If there is a better method to do this please do let me know.

Should be merged with: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2128

2023-07-09 21:31 UTC, wlhlm requested changes
Code looks good! Thanks for fixing old bugs 😄

This needs a new GT release and a subsequent update of the dependencies.

2023-07-09 21:55 UTC, wlhlm requested changes
Tested in game. An LV boiler now correctly vents at 64B instead of 32B. However, the steam fill bar in the GUI still tops out at 32B as reported in the original ticket. Can you look into this as well?

2023-07-10 07:11 UTC, Lyfts commented
Of course I forget the gui. Should be an easy fix.

2023-07-10 16:28 UTC, Lyfts commented
There might be a better way to do this but it renders correctly now.

2023-07-10 16:36 UTC, Dream-Master commented
@Lyfts can you run spotless ?

2023-07-11 15:20 UTC, Lyfts commented
As discussed [this pr](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2131) makes GT5 understand `getSteamCapacity()` which also obsoletes most of the previous fixes to the GT++ boilers.
Both GT5 and GT++ boilers are tested and working.

2023-07-11 17:11 UTC, wlhlm approved these changes
Thank you!

2023-07-11 17:21 UTC, merged