Fixed bee frames to make sense with additive production modifiers
GTNH-Museum/GTplusplus pull request #691
Opened 2023-07-14 20:17 UTC by hacatu

See https://github.com/GTNewHorizons/ForestryMC/pull/55

2023-07-17 09:18 UTC, kuba6000 requested changes
Please adjust all frames, not only negative ones.
1.5x -> +0.5
2x -> +1

2023-07-18 15:31 UTC, kuba6000 approved these changes

2023-07-18 18:20 UTC, Runakai1 approved these changes

2023-07-18 18:32 UTC, Dream-Master approved these changes

2023-07-18 18:32 UTC, merged